services:
  db: 
    image: postgres:16-alpine

    container_name: db-comics-dev
    
    environment:
      POSTGRES_DB: comics_store
      POSTGRES_USER: comics_user_dev
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
    
    volumes:
      - comics_data_db_dev:/var/lib/postgresql/data
    
    ports:
      - "5432:5432"
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10


  api:
    image: comics-api-server:1.0-dev
    
    build:
      context: .
    
    container_name: comics-api-dev
    
    depends_on:
      db:
        condition: service_healthy
    
    environment:
      FLASK_APP: main:create_app
      FLASK_ENV: development
      FLASK_DEBUG: 1
      DATABASE_URI: postgresql+psycopg2://comics_user_dev:${POSTGRES_PASSWORD:-123456}@db:5432/comics_store


    ports:
      - "8080:8080"
    
    command: ["flask", "run", "--host=0.0.0.0", "--port=8080"]

volumes:
  comics_data_db_dev:

